openapi: "3.0.0"
info:
  title: "Swagger Scheduler"
  version: "1.0.0"
paths:
  /email/exists:
    get:
      summary: "Check if verified email exists"
      parameters:
        - name: email
          in: query
          # allowReserved: true
          required: true
          schema:
            $ref: "#/components/schemas/Email"
      responses:
        "200":
          $ref: "#/components/responses/GetEmailExists200"
          description: "Check if user by specified email exist"
  /auth/signin:
    post:
      summary: "Sign in a user"
      requestBody:
        $ref: "#/components/requestBodies/AuthEmailCreds"
      responses:
        "200":
          $ref: "#/components/responses/User"
  /auth/signup:
    post:
      requestBody:
        $ref: "#/components/requestBodies/AuthEmailCreds"
      responses:
        "200":
          $ref: "#/components/responses/User"
  /auth/signout:
    post:
      responses:
        "204":
          description: "User signed out"
  /auth/verify:
    post:
      summary: "Verify email"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  $ref: "#/components/schemas/Code"
                userId:
                  $ref: "#/components/schemas/Id"
              required:
                - code
                - userId
      responses:
        "200":
          description: OK
  /auth/session:
    get:
      summary: "Check user`s session"
      responses:
        "200":
          $ref: "#/components/responses/User"
  /auth/resend:
    post:
      summary: "Resend verification code"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  $ref: "#/components/schemas/Email"
                userId:
                  $ref: "#/components/schemas/Id"
              required:
                - email
                - userId
      responses:
        "200":
          description: OK
  #*project endpoints
  /project:
    get:
      responses:
        "200":
          description: "Get user's public projects"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      $ref: "#/components/schemas/Id"
                    name:
                      type: string
                    createdBy:
                      $ref: "#/components/schemas/Id"
                    isPrivate:
                      type: boolean
                    lists:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                          projectId:
                            type: string
                          createdAt:
                            type: string
                          createdBy:
                            type: string
                          isPrivate:
                            type: boolean
                        required:
                          - id
                          - name
                          - projectId
                          - createdAt
                          - createdBy
                          - isPrivate
                  required:
                    - id
                    - name
                    - createdBy
                    - lists
                    - isPrivate
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        "200":
          description: "Create project"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
  /project/private:
    get:
      responses:
        "200":
          description: "Get private project with private list"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/Id"
                  name:
                    type: string
                  createdBy:
                    $ref: "#/components/schemas/Id"
                  isPrivate:
                    type: boolean
                  list:
                    $ref: "#/components/schemas/List"
                required:
                  - id
                  - name
                  - createdBy
                  - isPrivate
                  - list
  #*invitation endpoints
  /invitation:
    get:
      responses:
        "200":
          description: "Get invitations"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InvitationDto"
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                projectId:
                  type: string
              required:
                - email
                - projectId
      responses:
        "200":
          description: OK
  #*List endpoints
  /lists/{id}/tasks:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Id"
      responses:
        "200":
          description: "Get tasks"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TaskDto"
  /lists/{list_id}/tasks/{task_id}:
    put:
      parameters:
        - name: list_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Id"
        - name: task_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                  nullable: true
                status:
                  $ref: "#/components/schemas/TaskStatus"
                priority:
                  $ref: "#/components/schemas/Priority"
                start_date:
                  type: string
                  nullable: true
                due_date:
                  type: string
                  nullable: true
                type:
                  $ref: "#/components/schemas/TaskType"
      responses:
        "200":
          description: "Update task"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDto"

  #*task endpoints
  /tasks:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskFields"
      responses:
        "200":
          description: "Create task"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDto"
    delete:
      summary: Delete all trashed tasks
      responses:
        "200":
          description: OK
  /tasks/{id}:
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskFields"
      responses:
        "200":
          description: "Update task fields"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDto"
    delete:
      summary: Delete trashed task by taskId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Id"
      responses:
        "200":
          description: OK
  # /tasks/{id}/date:
  #   patch:
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         schema:
  #           $ref: "#/components/schemas/Id"
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               start_date:
  #                 $ref: "#/components/schemas/StartDate"
  #               due_date:
  #                 $ref: "#/components/schemas/DueDate"
  #             required:
  #               - start_date
  #               - due_date
  #     responses:
  #       "200":
  #         description: "Update task's start_date and due_date"
  #         content:
  #           application/json:
  #             schema:
  #               $ref: "#/components/schemas/TaskDto"
  # /tasks/{id}/status:
  #   patch:
  #     parameters:
  #       - name: id
  #         in: path
  #         schema:
  #           $ref: "#/components/schemas/Id"
  #         required: true
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               status:
  #                 $ref: "#/components/schemas/TaskStatus"
  #             required:
  #               - status
  #     responses:
  #       "200":
  #         description: OK
  # /tasks/{id}/priority:
  #   patch:
  #     parameters:
  #       - name: id
  #         in: path
  #         schema:
  #           $ref: "#/components/schemas/Id"
  #         required: true
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               priority:
  #                 $ref: "#/components/schemas/Priority"
  #             required:
  #               - priority
  #     responses:
  #       "200":
  #         description: OK
  /tasks/{id}/trash:
    post:
      parameters:
        - name: id
          in: path
          schema:
            $ref: "#/components/schemas/Id"
          required: true
      responses:
        "200":
          description: OK

components:
  responses:
    GetEmailExists200:
      description: "Check if user is present with such email"
      content:
        application/json:
          schema:
            type: object
            properties:
              exists:
                type: boolean
            required:
              - exists
    User:
      description: "User response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UserDto"

  schemas:
    Description:
      type: string
      nullable: true
    StartDate:
      type: string
      nullable: true
    DueDate:
      type: string
      nullable: true
    Email:
      type: string
      format: email
      description: "Email address"
      minLength: 4
    Code:
      type: string
      minLength: 6
      maxLength: 6
    Id:
      type: string
      format: uuid
    UuidOrEmpty:
      oneOf:
        - type: string
          format: uuid
        - type: string
          enum: [""]
    UserDto:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        email:
          $ref: "#/components/schemas/Email"
        verified:
          type: boolean
        createdAt:
          type: string
      required:
        - id
        - email
        - verified
        - createdAt
    TaskStatus:
      type: string
      enum:
        - inprogress
        - finished
        - todo
    TaskType:
      type: string
      enum:
        - inbox
        - unplaced
    Project:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        name:
          type: string
        createdBy:
          $ref: "#/components/schemas/Id"
        isPrivate:
          type: boolean
        lists:
          type: array
          items:
            $ref: "#/components/schemas/List"
      required:
        - id
        - name
        - createdBy
        - isPrivate
        - lists
    Priority:
      type: string
      enum:
        - none
        - low
        - normal
        - high
        - urgent
    TaskFields:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
          nullable: true
        status:
          $ref: "#/components/schemas/TaskStatus"
        priority:
          $ref: "#/components/schemas/Priority"
        start_date:
          type: string
          nullable: true
        due_date:
          type: string
          nullable: true
        list_id:
          type: string
        type:
          $ref: "#/components/schemas/TaskType"
      required:
        - title
        - description
        - status
        - start_date
        - due_date
        - type
        - priority
        - list_id
    TaskDto:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        title:
          type: string
        description:
          type: string
          nullable: true
        status:
          $ref: "#/components/schemas/TaskStatus"
        start_date:
          type: string
          nullable: true
        due_date:
          type: string
          nullable: true
        user_id:
          $ref: "#/components/schemas/Id"
        list_id:
          $ref: "#/components/schemas/Id"
        type:
          $ref: "#/components/schemas/TaskType"
        date_created:
          type: string
        is_trashed:
          type: boolean
        priority:
          $ref: "#/components/schemas/Priority"
      required:
        - id
        - title
        - description
        - status
        - start_date
        - due_date
        - user_id
        - type
        - date_created
        - is_trashed
        - list_id
        - priority
    List:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        createdBy:
          $ref: "#/components/schemas/Id"
        projectId:
          $ref: "#/components/schemas/UuidOrEmpty"
        createdAt:
          type: string
        isPrivate:
          type: boolean
      required:
        - isPrivate
        - createdAt
        - projectId
        - createdBy
        - name
        - id

    InvitationDto:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        invitedBy:
          $ref: "#/components/schemas/Id"
        userId:
          $ref: "#/components/schemas/Id"
        projectId:
          $ref: "#/components/schemas/Id"
        invitedAt:
          type: string
      required:
        - id
        - invitedBy
        - userId
        - projectId
        - invitedAt

  requestBodies:
    AuthEmailCreds:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                $ref: "#/components/schemas/Email"
              password:
                type: string
            required:
              - email
              - password
