/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Swagger Scheduler
 * OpenAPI spec version: 1.0.0
 */
/**
 * @nullable
 */
export type Description = string | null;

/**
 * @nullable
 */
export type StartDate = string | null;

/**
 * @nullable
 */
export type DueDate = string | null;

/**
 * Email address
 * @minLength 4
 */
export type Email = string;

/**
 * @minLength 6
 * @maxLength 6
 */
export type Code = string;

export type Id = string;

export type UuidOrEmpty = string | '';

export interface UserDto {
  id: Id;
  email: Email;
  verified: boolean;
  createdAt: string;
}

export type TaskStatus = typeof TaskStatus[keyof typeof TaskStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskStatus = {
  inprogress: 'inprogress',
  finished: 'finished',
  todo: 'todo',
} as const;

export type TaskType = typeof TaskType[keyof typeof TaskType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskType = {
  inbox: 'inbox',
  unplaced: 'unplaced',
} as const;

export interface Project {
  id: Id;
  name: string;
  createdBy: Id;
  isPrivate: boolean;
  lists: List[];
}

export type Priority = typeof Priority[keyof typeof Priority];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Priority = {
  none: 'none',
  low: 'low',
  normal: 'normal',
  high: 'high',
  urgent: 'urgent',
} as const;

export interface TaskFields {
  title: string;
  /** @nullable */
  description: string | null;
  status: TaskStatus;
  priority: Priority;
  /** @nullable */
  start_date: string | null;
  /** @nullable */
  due_date: string | null;
  list_id: string;
  type: TaskType;
}

export interface TaskDto {
  id: Id;
  title: string;
  /** @nullable */
  description: string | null;
  status: TaskStatus;
  /** @nullable */
  start_date: string | null;
  /** @nullable */
  due_date: string | null;
  user_id: Id;
  list_id: Id;
  type: TaskType;
  date_created: string;
  is_trashed: boolean;
  priority: Priority;
}

export interface List {
  id: string;
  name: string;
  createdBy: Id;
  projectId: UuidOrEmpty;
  createdAt: string;
  isPrivate: boolean;
}

export interface InvitationDto {
  id: Id;
  invitedBy: Id;
  userId: Id;
  projectId: Id;
  invitedAt: string;
}

export type GetEmailExists200Response = {
  exists: boolean;
};

/**
 * User response
 */
export type UserResponse = UserDto;

export type AuthEmailCredsBody = {
  email: Email;
  password: string;
};

export type GetEmailExistsParams = {
email: Email;
};

export type PostAuthVerifyBody = {
  code: Code;
  userId: Id;
};

export type PostAuthResendBody = {
  email: Email;
  userId: Id;
};

export type GetProject200ItemListsItem = {
  id: string;
  name: string;
  projectId: string;
  createdAt: string;
  createdBy: string;
  isPrivate: boolean;
};

export type GetProject200Item = {
  id: Id;
  name: string;
  createdBy: Id;
  isPrivate: boolean;
  lists: GetProject200ItemListsItem[];
};

export type PostProjectBody = {
  name: string;
};

export type GetProjectPrivate200 = {
  id: Id;
  name: string;
  createdBy: Id;
  isPrivate: boolean;
  list: List;
};

export type PostInvitationBody = {
  email: string;
  projectId: string;
};

export type PutListsListIdTasksTaskIdBody = {
  title?: string;
  /** @nullable */
  description?: string | null;
  status?: TaskStatus;
  priority?: Priority;
  /** @nullable */
  start_date?: string | null;
  /** @nullable */
  due_date?: string | null;
  type?: TaskType;
};

