/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Swagger Scheduler
 * OpenAPI spec version: 1.0.0
 */
export type PatchTasksIdStatusBody = {
  status: TaskStatus
}

export type PatchTasksIdDateBody = {
  due_date: DueDate
  start_date: StartDate
}

export type PostAuthResendBody = {
  email: Email
  userId: Id
}

export type GetEmailExistsParams = {
  email: Email
}

export type AuthEmailCredsBody = {
  email: Email
  password: string
}

export type GetEmailExists200Response = {
  exists: boolean
}

export type TaskType = (typeof TaskType)[keyof typeof TaskType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskType = {
  inbox: "inbox",
  unplaced: "unplaced",
} as const

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskStatus = {
  inprogress: "inprogress",
  finished: "finished",
} as const

export interface TaskDto {
  date_created: string
  /** @nullable */
  description: string | null
  /** @nullable */
  due_date: number | null
  id: Id
  is_trashed: boolean
  /** @nullable */
  start_date: number | null
  status: TaskStatus
  title: string
  type: TaskType
  user_id: Id
}

export interface TaskFields {
  /** @nullable */
  description: string | null
  /** @nullable */
  due_date: number | null
  /** @nullable */
  start_date: number | null
  status: TaskStatus
  title: string
  type: TaskType
}

export type Id = string

export type PostAuthVerifyBody = {
  code: Code
  userId: Id
}

export interface UserDto {
  email: Email
  id: Id
  verified: boolean
}

/**
 * User response
 */
export type UserResponse = UserDto

/**
 * @minLength 6
 * @maxLength 6
 */
export type Code = string

/**
 * Email address
 * @minLength 4
 */
export type Email = string

/**
 * @nullable
 */
export type DueDate = number | null

/**
 * @nullable
 */
export type StartDate = number | null

/**
 * @nullable
 */
export type Description = string | null
