/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Swagger Scheduler
 * OpenAPI spec version: 1.0.0
 */
import type {
  AuthEmailCredsBody,
  GetEmailExists200Response,
  GetEmailExistsParams,
  GetProject200Item,
  GetProjectPrivate200,
  Id,
  InvitationDto,
  PostAuthResendBody,
  PostAuthVerifyBody,
  PostInvitationBody,
  PostProjectBody,
  Project,
  PutListsListIdTasksTaskIdBody,
  TaskDto,
  TaskFields,
  UserResponse
} from './scheduler.schemas';

import getEmailExistsMutator from './fetch';
import postAuthSigninMutator from './fetch';
import postAuthSignupMutator from './fetch';
import postAuthSignoutMutator from './fetch';
import postAuthVerifyMutator from './fetch';
import getAuthSessionMutator from './fetch';
import postAuthResendMutator from './fetch';
import getProjectMutator from './fetch';
import postProjectMutator from './fetch';
import getProjectPrivateMutator from './fetch';
import getInvitationMutator from './fetch';
import postInvitationMutator from './fetch';
import getListsIdTasksMutator from './fetch';
import putListsListIdTasksTaskIdMutator from './fetch';
import postTasksMutator from './fetch';
import deleteTasksMutator from './fetch';
import putTasksIdMutator from './fetch';
import deleteTasksIdMutator from './fetch';
import postTasksIdTrashMutator from './fetch';

/**
 * @summary Check if verified email exists
 */
export type getEmailExistsResponse200 = {
  data: GetEmailExists200Response
  status: 200
}
    
export type getEmailExistsResponseSuccess = (getEmailExistsResponse200) & {
  headers: Headers;
};
;

export type getEmailExistsResponse = (getEmailExistsResponseSuccess)

export const getGetEmailExistsUrl = (params: GetEmailExistsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/email/exists?${stringifiedParams}` : `/email/exists`
}

export const getEmailExists = async (params: GetEmailExistsParams, options?: RequestInit): Promise<getEmailExistsResponse> => {
  
  return getEmailExistsMutator<getEmailExistsResponse>(getGetEmailExistsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Sign in a user
 */
export type postAuthSigninResponse200 = {
  data: UserResponse
  status: 200
}
    
export type postAuthSigninResponseSuccess = (postAuthSigninResponse200) & {
  headers: Headers;
};
;

export type postAuthSigninResponse = (postAuthSigninResponseSuccess)

export const getPostAuthSigninUrl = () => {


  

  return `/auth/signin`
}

export const postAuthSignin = async (authEmailCredsBody: AuthEmailCredsBody, options?: RequestInit): Promise<postAuthSigninResponse> => {
  
  return postAuthSigninMutator<postAuthSigninResponse>(getPostAuthSigninUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authEmailCredsBody,)
  }
);}



export type postAuthSignupResponse200 = {
  data: UserResponse
  status: 200
}
    
export type postAuthSignupResponseSuccess = (postAuthSignupResponse200) & {
  headers: Headers;
};
;

export type postAuthSignupResponse = (postAuthSignupResponseSuccess)

export const getPostAuthSignupUrl = () => {


  

  return `/auth/signup`
}

export const postAuthSignup = async (authEmailCredsBody: AuthEmailCredsBody, options?: RequestInit): Promise<postAuthSignupResponse> => {
  
  return postAuthSignupMutator<postAuthSignupResponse>(getPostAuthSignupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authEmailCredsBody,)
  }
);}



export type postAuthSignoutResponse204 = {
  data: void
  status: 204
}
    
export type postAuthSignoutResponseSuccess = (postAuthSignoutResponse204) & {
  headers: Headers;
};
;

export type postAuthSignoutResponse = (postAuthSignoutResponseSuccess)

export const getPostAuthSignoutUrl = () => {


  

  return `/auth/signout`
}

export const postAuthSignout = async ( options?: RequestInit): Promise<postAuthSignoutResponse> => {
  
  return postAuthSignoutMutator<postAuthSignoutResponse>(getPostAuthSignoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Verify email
 */
export type postAuthVerifyResponse200 = {
  data: void
  status: 200
}
    
export type postAuthVerifyResponseSuccess = (postAuthVerifyResponse200) & {
  headers: Headers;
};
;

export type postAuthVerifyResponse = (postAuthVerifyResponseSuccess)

export const getPostAuthVerifyUrl = () => {


  

  return `/auth/verify`
}

export const postAuthVerify = async (postAuthVerifyBody: PostAuthVerifyBody, options?: RequestInit): Promise<postAuthVerifyResponse> => {
  
  return postAuthVerifyMutator<postAuthVerifyResponse>(getPostAuthVerifyUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postAuthVerifyBody,)
  }
);}



/**
 * @summary Check user`s session
 */
export type getAuthSessionResponse200 = {
  data: UserResponse
  status: 200
}
    
export type getAuthSessionResponseSuccess = (getAuthSessionResponse200) & {
  headers: Headers;
};
;

export type getAuthSessionResponse = (getAuthSessionResponseSuccess)

export const getGetAuthSessionUrl = () => {


  

  return `/auth/session`
}

export const getAuthSession = async ( options?: RequestInit): Promise<getAuthSessionResponse> => {
  
  return getAuthSessionMutator<getAuthSessionResponse>(getGetAuthSessionUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Resend verification code
 */
export type postAuthResendResponse200 = {
  data: void
  status: 200
}
    
export type postAuthResendResponseSuccess = (postAuthResendResponse200) & {
  headers: Headers;
};
;

export type postAuthResendResponse = (postAuthResendResponseSuccess)

export const getPostAuthResendUrl = () => {


  

  return `/auth/resend`
}

export const postAuthResend = async (postAuthResendBody: PostAuthResendBody, options?: RequestInit): Promise<postAuthResendResponse> => {
  
  return postAuthResendMutator<postAuthResendResponse>(getPostAuthResendUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postAuthResendBody,)
  }
);}



export type getProjectResponse200 = {
  data: GetProject200Item[]
  status: 200
}
    
export type getProjectResponseSuccess = (getProjectResponse200) & {
  headers: Headers;
};
;

export type getProjectResponse = (getProjectResponseSuccess)

export const getGetProjectUrl = () => {


  

  return `/project`
}

export const getProject = async ( options?: RequestInit): Promise<getProjectResponse> => {
  
  return getProjectMutator<getProjectResponse>(getGetProjectUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type postProjectResponse200 = {
  data: Project
  status: 200
}
    
export type postProjectResponseSuccess = (postProjectResponse200) & {
  headers: Headers;
};
;

export type postProjectResponse = (postProjectResponseSuccess)

export const getPostProjectUrl = () => {


  

  return `/project`
}

export const postProject = async (postProjectBody: PostProjectBody, options?: RequestInit): Promise<postProjectResponse> => {
  
  return postProjectMutator<postProjectResponse>(getPostProjectUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postProjectBody,)
  }
);}



export type getProjectPrivateResponse200 = {
  data: GetProjectPrivate200
  status: 200
}
    
export type getProjectPrivateResponseSuccess = (getProjectPrivateResponse200) & {
  headers: Headers;
};
;

export type getProjectPrivateResponse = (getProjectPrivateResponseSuccess)

export const getGetProjectPrivateUrl = () => {


  

  return `/project/private`
}

export const getProjectPrivate = async ( options?: RequestInit): Promise<getProjectPrivateResponse> => {
  
  return getProjectPrivateMutator<getProjectPrivateResponse>(getGetProjectPrivateUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type getInvitationResponse200 = {
  data: InvitationDto[]
  status: 200
}
    
export type getInvitationResponseSuccess = (getInvitationResponse200) & {
  headers: Headers;
};
;

export type getInvitationResponse = (getInvitationResponseSuccess)

export const getGetInvitationUrl = () => {


  

  return `/invitation`
}

export const getInvitation = async ( options?: RequestInit): Promise<getInvitationResponse> => {
  
  return getInvitationMutator<getInvitationResponse>(getGetInvitationUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type postInvitationResponse200 = {
  data: void
  status: 200
}
    
export type postInvitationResponseSuccess = (postInvitationResponse200) & {
  headers: Headers;
};
;

export type postInvitationResponse = (postInvitationResponseSuccess)

export const getPostInvitationUrl = () => {


  

  return `/invitation`
}

export const postInvitation = async (postInvitationBody: PostInvitationBody, options?: RequestInit): Promise<postInvitationResponse> => {
  
  return postInvitationMutator<postInvitationResponse>(getPostInvitationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postInvitationBody,)
  }
);}



export type getListsIdTasksResponse200 = {
  data: TaskDto[]
  status: 200
}
    
export type getListsIdTasksResponseSuccess = (getListsIdTasksResponse200) & {
  headers: Headers;
};
;

export type getListsIdTasksResponse = (getListsIdTasksResponseSuccess)

export const getGetListsIdTasksUrl = (id: Id,) => {


  

  return `/lists/${id}/tasks`
}

export const getListsIdTasks = async (id: Id, options?: RequestInit): Promise<getListsIdTasksResponse> => {
  
  return getListsIdTasksMutator<getListsIdTasksResponse>(getGetListsIdTasksUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type putListsListIdTasksTaskIdResponse200 = {
  data: TaskDto
  status: 200
}
    
export type putListsListIdTasksTaskIdResponseSuccess = (putListsListIdTasksTaskIdResponse200) & {
  headers: Headers;
};
;

export type putListsListIdTasksTaskIdResponse = (putListsListIdTasksTaskIdResponseSuccess)

export const getPutListsListIdTasksTaskIdUrl = (listId: Id,
    taskId: Id,) => {


  

  return `/lists/${listId}/tasks/${taskId}`
}

export const putListsListIdTasksTaskId = async (listId: Id,
    taskId: Id,
    putListsListIdTasksTaskIdBody: PutListsListIdTasksTaskIdBody, options?: RequestInit): Promise<putListsListIdTasksTaskIdResponse> => {
  
  return putListsListIdTasksTaskIdMutator<putListsListIdTasksTaskIdResponse>(getPutListsListIdTasksTaskIdUrl(listId,taskId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putListsListIdTasksTaskIdBody,)
  }
);}



export type postTasksResponse200 = {
  data: TaskDto
  status: 200
}
    
export type postTasksResponseSuccess = (postTasksResponse200) & {
  headers: Headers;
};
;

export type postTasksResponse = (postTasksResponseSuccess)

export const getPostTasksUrl = () => {


  

  return `/tasks`
}

export const postTasks = async (taskFields: TaskFields, options?: RequestInit): Promise<postTasksResponse> => {
  
  return postTasksMutator<postTasksResponse>(getPostTasksUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      taskFields,)
  }
);}



/**
 * @summary Delete all trashed tasks
 */
export type deleteTasksResponse200 = {
  data: void
  status: 200
}
    
export type deleteTasksResponseSuccess = (deleteTasksResponse200) & {
  headers: Headers;
};
;

export type deleteTasksResponse = (deleteTasksResponseSuccess)

export const getDeleteTasksUrl = () => {


  

  return `/tasks`
}

export const deleteTasks = async ( options?: RequestInit): Promise<deleteTasksResponse> => {
  
  return deleteTasksMutator<deleteTasksResponse>(getDeleteTasksUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



export type putTasksIdResponse200 = {
  data: TaskDto
  status: 200
}
    
export type putTasksIdResponseSuccess = (putTasksIdResponse200) & {
  headers: Headers;
};
;

export type putTasksIdResponse = (putTasksIdResponseSuccess)

export const getPutTasksIdUrl = (id: Id,) => {


  

  return `/tasks/${id}`
}

export const putTasksId = async (id: Id,
    taskFields: TaskFields, options?: RequestInit): Promise<putTasksIdResponse> => {
  
  return putTasksIdMutator<putTasksIdResponse>(getPutTasksIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      taskFields,)
  }
);}



/**
 * @summary Delete trashed task by taskId
 */
export type deleteTasksIdResponse200 = {
  data: void
  status: 200
}
    
export type deleteTasksIdResponseSuccess = (deleteTasksIdResponse200) & {
  headers: Headers;
};
;

export type deleteTasksIdResponse = (deleteTasksIdResponseSuccess)

export const getDeleteTasksIdUrl = (id: Id,) => {


  

  return `/tasks/${id}`
}

export const deleteTasksId = async (id: Id, options?: RequestInit): Promise<deleteTasksIdResponse> => {
  
  return deleteTasksIdMutator<deleteTasksIdResponse>(getDeleteTasksIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



export type postTasksIdTrashResponse200 = {
  data: void
  status: 200
}
    
export type postTasksIdTrashResponseSuccess = (postTasksIdTrashResponse200) & {
  headers: Headers;
};
;

export type postTasksIdTrashResponse = (postTasksIdTrashResponseSuccess)

export const getPostTasksIdTrashUrl = (id: Id,) => {


  

  return `/tasks/${id}/trash`
}

export const postTasksIdTrash = async (id: Id, options?: RequestInit): Promise<postTasksIdTrashResponse> => {
  
  return postTasksIdTrashMutator<postTasksIdTrashResponse>(getPostTasksIdTrashUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



