/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Swagger Scheduler
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Check if verified email exists
 */
export const getEmailExistsQueryEmailMin = 4;



export const getEmailExistsQueryParams = zod.object({
  "email": zod.email().min(getEmailExistsQueryEmailMin)
})

export const getEmailExistsResponse = zod.object({
  "exists": zod.boolean()
})


/**
 * @summary Sign in a user
 */
export const postAuthSigninBodyEmailMin = 4;



export const postAuthSigninBody = zod.object({
  "email": zod.email().min(postAuthSigninBodyEmailMin).describe('Email address'),
  "password": zod.string()
})

export const postAuthSigninResponseEmailMin = 4;



export const postAuthSigninResponse = zod.object({
  "id": zod.uuid(),
  "email": zod.email().min(postAuthSigninResponseEmailMin).describe('Email address'),
  "verified": zod.boolean(),
  "createdAt": zod.string()
})


export const postAuthSignupBodyEmailMin = 4;



export const postAuthSignupBody = zod.object({
  "email": zod.email().min(postAuthSignupBodyEmailMin).describe('Email address'),
  "password": zod.string()
})

export const postAuthSignupResponseEmailMin = 4;



export const postAuthSignupResponse = zod.object({
  "id": zod.uuid(),
  "email": zod.email().min(postAuthSignupResponseEmailMin).describe('Email address'),
  "verified": zod.boolean(),
  "createdAt": zod.string()
})


/**
 * @summary Verify email
 */
export const postAuthVerifyBodyCodeMin = 6;
export const postAuthVerifyBodyCodeMax = 6;



export const postAuthVerifyBody = zod.object({
  "code": zod.string().min(postAuthVerifyBodyCodeMin).max(postAuthVerifyBodyCodeMax),
  "userId": zod.uuid()
})


/**
 * @summary Check user`s session
 */
export const getAuthSessionResponseEmailMin = 4;



export const getAuthSessionResponse = zod.object({
  "id": zod.uuid(),
  "email": zod.email().min(getAuthSessionResponseEmailMin).describe('Email address'),
  "verified": zod.boolean(),
  "createdAt": zod.string()
})


/**
 * @summary Resend verification code
 */
export const postAuthResendBodyEmailMin = 4;



export const postAuthResendBody = zod.object({
  "email": zod.email().min(postAuthResendBodyEmailMin).describe('Email address'),
  "userId": zod.uuid()
})


export const getProjectResponseItem = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "createdBy": zod.uuid(),
  "isPrivate": zod.boolean(),
  "lists": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "projectId": zod.string(),
  "createdAt": zod.string(),
  "createdBy": zod.string(),
  "isPrivate": zod.boolean()
}))
})
export const getProjectResponse = zod.array(getProjectResponseItem)


export const postProjectBody = zod.object({
  "name": zod.string()
})

export const postProjectResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "createdBy": zod.uuid(),
  "isPrivate": zod.boolean(),
  "lists": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "createdBy": zod.uuid(),
  "projectId": zod.union([zod.uuid(),zod.enum([''])]),
  "createdAt": zod.string(),
  "isPrivate": zod.boolean()
}))
})


export const getProjectPrivateResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "createdBy": zod.uuid(),
  "isPrivate": zod.boolean(),
  "list": zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "createdBy": zod.uuid(),
  "projectId": zod.union([zod.uuid(),zod.enum([''])]),
  "createdAt": zod.string(),
  "isPrivate": zod.boolean()
})
})


export const getInvitationResponseItem = zod.object({
  "id": zod.uuid(),
  "invitedBy": zod.uuid(),
  "userId": zod.uuid(),
  "projectId": zod.uuid(),
  "invitedAt": zod.string()
})
export const getInvitationResponse = zod.array(getInvitationResponseItem)


export const postInvitationBody = zod.object({
  "email": zod.string(),
  "projectId": zod.string()
})


export const getListsIdTasksParams = zod.object({
  "id": zod.uuid()
})

export const getListsIdTasksResponseItem = zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "status": zod.enum(['inprogress', 'finished', 'todo']),
  "start_date": zod.string().nullable(),
  "due_date": zod.string().nullable(),
  "user_id": zod.uuid(),
  "list_id": zod.uuid(),
  "type": zod.enum(['inbox', 'unplaced']),
  "date_created": zod.string(),
  "is_trashed": zod.boolean(),
  "priority": zod.enum(['none', 'low', 'normal', 'high', 'urgent'])
})
export const getListsIdTasksResponse = zod.array(getListsIdTasksResponseItem)


export const putListsListIdTasksTaskIdParams = zod.object({
  "list_id": zod.uuid(),
  "task_id": zod.uuid()
})

export const putListsListIdTasksTaskIdBody = zod.object({
  "title": zod.string().optional(),
  "description": zod.string().nullish(),
  "status": zod.enum(['inprogress', 'finished', 'todo']).optional(),
  "priority": zod.enum(['none', 'low', 'normal', 'high', 'urgent']).optional(),
  "start_date": zod.string().nullish(),
  "due_date": zod.string().nullish(),
  "type": zod.enum(['inbox', 'unplaced']).optional()
})

export const putListsListIdTasksTaskIdResponse = zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "status": zod.enum(['inprogress', 'finished', 'todo']),
  "start_date": zod.string().nullable(),
  "due_date": zod.string().nullable(),
  "user_id": zod.uuid(),
  "list_id": zod.uuid(),
  "type": zod.enum(['inbox', 'unplaced']),
  "date_created": zod.string(),
  "is_trashed": zod.boolean(),
  "priority": zod.enum(['none', 'low', 'normal', 'high', 'urgent'])
})


export const postTasksBody = zod.object({
  "title": zod.string(),
  "description": zod.string().nullable(),
  "status": zod.enum(['inprogress', 'finished', 'todo']),
  "priority": zod.enum(['none', 'low', 'normal', 'high', 'urgent']),
  "start_date": zod.string().nullable(),
  "due_date": zod.string().nullable(),
  "list_id": zod.string(),
  "type": zod.enum(['inbox', 'unplaced'])
})

export const postTasksResponse = zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "status": zod.enum(['inprogress', 'finished', 'todo']),
  "start_date": zod.string().nullable(),
  "due_date": zod.string().nullable(),
  "user_id": zod.uuid(),
  "list_id": zod.uuid(),
  "type": zod.enum(['inbox', 'unplaced']),
  "date_created": zod.string(),
  "is_trashed": zod.boolean(),
  "priority": zod.enum(['none', 'low', 'normal', 'high', 'urgent'])
})


export const putTasksIdParams = zod.object({
  "id": zod.uuid()
})

export const putTasksIdBody = zod.object({
  "title": zod.string(),
  "description": zod.string().nullable(),
  "status": zod.enum(['inprogress', 'finished', 'todo']),
  "priority": zod.enum(['none', 'low', 'normal', 'high', 'urgent']),
  "start_date": zod.string().nullable(),
  "due_date": zod.string().nullable(),
  "list_id": zod.string(),
  "type": zod.enum(['inbox', 'unplaced'])
})

export const putTasksIdResponse = zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "status": zod.enum(['inprogress', 'finished', 'todo']),
  "start_date": zod.string().nullable(),
  "due_date": zod.string().nullable(),
  "user_id": zod.uuid(),
  "list_id": zod.uuid(),
  "type": zod.enum(['inbox', 'unplaced']),
  "date_created": zod.string(),
  "is_trashed": zod.boolean(),
  "priority": zod.enum(['none', 'low', 'normal', 'high', 'urgent'])
})


/**
 * @summary Delete trashed task by taskId
 */
export const deleteTasksIdParams = zod.object({
  "id": zod.uuid()
})


export const postTasksIdTrashParams = zod.object({
  "id": zod.uuid()
})
