name: scheduler

services:
  frontend:
    build: client/
    ports: 
      - "4173:4173"
  backend:
    build: server/
    ports:
      - "3000:3000"
    environment:
      - CLIENT_URL=${CLIENT_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - PASSWORD=${PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  redis:
    image: redis
    container_name: "my-redis"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 10s
      retries: 5
  mysql:
    image: mysql
    container_name: "database"
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=scheduler
    volumes:
      - C:/Users/User/dumps:/docker-entrypoint-initdb.d
    healthcheck: 
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -P 3306 -u root --silent']
      interval: 5s
      timeout: 10s
      retries: 5 