name: Docker

on: 
  push:
    branches:
      - main

jobs:
  build-go-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: server/go.work
      - run: go build -C server/app/cmd main.go
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./server
          file: ./server/app/Dockerfile
          cache-to: type=gha,mode=max
          cache-from: type=gha
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest

  build-web-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with: 
          node-version-file: client/package.json
          cache: 'yarn'
          cache-dependency-path: |
            client/package.json
            client/yarn.lock
      - name: Install deps
        run: cd client && yarn install --frozen-lockfile
      - name: Build web
        run: cd client && yarn build
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./client
          file: ./client/Dockerfile
          cache-to: type=gha,mode=max
          cache-from: type=gha
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web:latest
  migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./server
          file: ./server/migrations/Dockerfile
          cache-to: type=gha,mode=max
          cache-from: type=gha
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/migrations:latest