name: Docker

on: 
  push:
    branches:
      - main

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'server/go.work'
      - run: go build -C server/app/cmd main.go
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with: 
          node-version-file: client/package.json
          cache: 'yarn'
          cache-dependency-path: |
            client/package.json
            client/yarn.lock
      - name: Install deps
        run: yarn install --frozen-lockfile --prod
      - name: Build web
        run: cd client && yarn build