name: Scheduler CI

on:
  push:
    branches: [ "develop" ]

env:
  VITE_ORIGIN_URL: http://localhost:3000/
jobs:
  build:

    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: './client'
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install yarn
      run: npm install -g yarn
    - name: Setup node with yarn cache
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
        cache-dependency-path: './client/yarn.lock'
    - name: Install dependencies
      run: yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Generate build
      run: yarn build
    - name: Run tests
      run: yarn test
    - name: Run Playwright tests
      run: yarn playwright test --project chromium
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
