# name: Docker

# on: 
#   push:
#     branches:
#       - 'main'

# jobs:
#   web:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
    
      
# docker buildx

# login to docker registery

